name: Build and publish HTML

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        # checkout specific branch
        ref: main

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        version: latest

    - name: Set up Python
      run: uv python install

    - name: Install dependencies
      run: uv sync --frozen --no-dev

    - name: Build documentation
      run: make html

    - name: Publish HTML
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: ./build/html/*
        target: ${{ secrets.TARGETDIR }}
        strip_components: 2
        rm: true
